### ISSUE TITLE
Scala support?

### ISSUE THREAD

**Issue by grale88** [EventStore/EventStoreDB-Client-Java#63]
We have been using old client for implementing Scala event store applications and since we saw on official docs [page](https://developers.eventstore.com/server/v20/server/introduction/clients.html#tcp-protocol) that there is a plan to phase out old TCP clients, we were wondering if we can use new official Java client (grpc) with Scala. Is there also any example of integration available? One of our concerns is serialization/deserialization of Scala case classes using Jackson JSON mapper.

**Comment by ahjohannessen** [comment]
I got one here https://github.com/ahjohannessen/sec :)

**Comment by grale88** [comment]
@ahjohannessen 

Sorry for the late reply. I checked the documentation for usage examples. Are there examples of reading/deleting events available somewhere on the repo?

I am also interested if this library can be used with Scala or it will be supported in the future, since it is an official client library.

**Comment by ahjohannessen** [comment]
@grale88 I got busy with other stuff, so I put that on pause, but will take it up soon.

> Sorry for the late reply. I checked the documentation for usage examples. Are there examples of reading/deleting events available somewhere on the repo?

For now there are a lot of integration tests, though optimized for DRY, so that might help.

> I am also interested if this library can be used with Scala

That should not be a big issue, but it comes with some “sad” things from Java, e.g. null usage, exceptions and so on - It is similar to the dotnet client. My client is based around FP and uses cats-effect and fs2, so there is a learning curve if those are foreign to you. I am sure you can use the official Java client and be happy with that :) Try them both and see what works best for you.

**Comment by YoEight** [comment]
We have no plan on providing a Scala client. However, we could accommodate the Java client to ease integration in a Scala codebase. What needs to be done to achieve that?
